### ISSUE TITLE
Device has error being added

### ISSUE THREAD

**Issue by earlthesquirrel** [ljezny/Particle-HAP#12]
A particle photon I have onboarded fine to start with, but after a 2nd remove, it stopped adding.
I tried the same code on another particle.  The Particle itself runs and is on Wifi just fine.
(I'm basically trying to build a motion sensor using a Particle Photon, PIR and your SW -- thought this would be a fairly simple exercise... and initially it was... but data from PIR wasn't making into characteristic... at least that's what it looked like)

I've checked the Particle events list... and it looks correct (see below) (I've removed my printouts which were interspersed).

homekit/close	192.168.1.174	motion-1	3/16/20 at 6:46:56 pm
homekit/accessory	192.168.1.174	motion-1	3/16/20 at 6:46:54 pm
homekit/accessory	192.168.1.174	motion-1	3/16/20 at 6:46:53 pm
homekit/pair-verify	192.168.1.174	motion-1	3/16/20 at 6:46:49 pm
homekit/pair-verify	192.168.1.174	motion-1	3/16/20 at 6:46:47 pm
homekit/accept	192.168.1.174	motion-1	3/16/20 at 6:46:47 pm
homekit/pair-setup	192.168.1.174	motion-1	3/16/20 at 6:46:44 pm
homekit/pair-setup	192.168.1.174	motion-1	3/16/20 at 6:46:39 pm
homekit/pair-setup	192.168.1.174	motion-1	3/16/20 at 6:46:34 pm
homekit/accept	192.168.1.174	motion-1	3/16/20 at 6:46:34 pm
spark/device/diagnostics/update	{"device":{"system":{"uptime":2,"memory":{"total":82944,"used":38792}},"network":{"connection":{"status":4,"error":0,"disconnects":0,"attempts":1,"disconnect":0},"signal":{"rssi":-47,"strength":100,"quality":100,"qualityv":45,"at":1,"strengthv":-47}},"cloud":{"connection":{"status":1,"error":0,"attempts":1,"disconnect":0},"disconnects":0,"publish":{"rate_limited":0},"coap":{"unack":0}}},"service":{"device":{"status":"ok"},"coap":{"round_trip":101},"cloud":{"uptime":0,"publish":{"sent":4}}}}	motion-1	3/16/20 at 6:46:27 pm

 I don't see any errors, but I get the following non-helpful screen on my iPhone.
(any thoughts?)
 "
![Erorr Screen](https://user-images.githubusercontent.com/4523243/76806271-4c991b80-67b7-11ea-9b4d-106e523e903e.png)

**Comment by ljezny** [comment]
Can you please provide full sample or at least full log. My particle-hap logs a lot. I strongly believe, that you have a bug in device description. Connect Photon via USB and catch whole log.

**Comment by earlthesquirrel** [comment]
0000036266 [homekit] INFO: Bonjour advertised
0000037268 [homekit] INFO: Bonjour advertised
0000038271 [homekit] INFO: Bonjour advertised
0000039274 [homekit] INFO: Bonjour advertised
0000040277 [homekit] INFO: Bonjour advertised
0000041280 [homekit] INFO: Bonjour advertised
0000042283 [homekit] INFO: Bonjour advertised
0000042284 [homekit] INFO: Client connected.
0000042285 [homekit] INFO: Request Message read length: 134 
0000042286 [homekit] INFO: Handling Pair Setup...
0000042287 [homekit] INFO: State: 1
0000042287 [homekit] INFO: Homekit progress callback: 1
0000042287 [homekit] INFO: State_M1_SRPStartRequest
0000046194 [homekit] INFO: Homekit progress callback: 2
0000046194 [homekit] INFO: writeData responseLen:489
0000047197 [homekit] INFO: Bonjour advertised
0000048201 [homekit] INFO: Bonjour advertised
0000049205 [homekit] INFO: Bonjour advertised
0000050209 [homekit] INFO: Bonjour advertised
0000051213 [homekit] INFO: Bonjour advertised
0000052217 [homekit] INFO: Bonjour advertised
0000053222 [homekit] INFO: Bonjour advertised
0000054225 [homekit] INFO: Bonjour advertised
0000055228 [homekit] INFO: Bonjour advertised
0000056232 [homekit] INFO: Bonjour advertised
0000057236 [homekit] INFO: Bonjour advertised
0000058240 [homekit] INFO: Bonjour advertised
0000059244 [homekit] INFO: Bonjour advertised
0000060248 [homekit] INFO: Bonjour advertised
0000061252 [homekit] INFO: Bonjour advertised
0000062256 [homekit] INFO: Bonjour advertised
0000063260 [homekit] INFO: Bonjour advertised
0000064264 [homekit] INFO: Bonjour advertised
0000065268 [homekit] INFO: Bonjour advertised
0000066272 [homekit] INFO: Bonjour advertised
0000069277 [homekit] INFO: Bonjour advertised
0000070280 [homekit] INFO: Bonjour advertised
0000071283 [homekit] INFO: Bonjour advertised
0000072287 [homekit] INFO: Bonjour advertised
0000073291 [homekit] INFO: Bonjour advertised
0000074295 [homekit] INFO: Bonjour advertised
0000075299 [homekit] INFO: Bonjour advertised
0000076303 [homekit] INFO: Bonjour advertised
0000077307 [homekit] INFO: Bonjour advertised
0000078311 [homekit] INFO: Bonjour advertised
0000079315 [homekit] INFO: Bonjour advertised
0000080319 [homekit] INFO: Bonjour advertised
0000081323 [homekit] INFO: Bonjour advertised
0000082327 [homekit] INFO: Bonjour advertised
0000083331 [homekit] INFO: Bonjour advertised
0000084335 [homekit] INFO: Bonjour advertised
0000085340 [homekit] INFO: Bonjour advertised
0000086343 [homekit] INFO: Bonjour advertised
0000087346 [homekit] INFO: Bonjour advertised
0000088350 [homekit] INFO: Bonjour advertised
0000089354 [homekit] INFO: Bonjour advertised
0000090358 [homekit] INFO: Bonjour advertised
0000091362 [homekit] INFO: Bonjour advertised
0000092366 [homekit] INFO: Bonjour advertised
0000093370 [homekit] INFO: Bonjour advertised
0000094374 [homekit] INFO: Bonjour advertised
0000095378 [homekit] INFO: Bonjour advertised
0000095380 [homekit] INFO: Request Message read length: 587 
0000095381 [homekit] INFO: Handling Pair Setup...
0000095382 [homekit] INFO: State: 3
0000095383 [homekit] INFO: State_M3_SRPVerifyRequest
0000095383 [homekit] INFO: Homekit progress callback: 3
0000099697 [homekit] INFO: Password is correct.
0000099697 [homekit] INFO: Homekit progress callback: 4
0000099698 [homekit] INFO: writeData responseLen:148
0000100701 [homekit] INFO: Bonjour advertised
0000100703 [homekit] INFO: Request Message read length: 289 
0000100704 [homekit] INFO: Handling Pair Setup...
0000100705 [homekit] INFO: State: 5
0000100705 [homekit] INFO: State_M5_ExchangeRequest
0000100706 [homekit] INFO: Homekit progress callback: 5
0000100708 [homekit] INFO: wc_ChaCha20Poly1305_Decrypt: r:0
0000100708 [homekit] INFO: Persistor: resetPairings
0000100708 [homekit] INFO: Persistor: save
0000100709 [homekit] INFO: Persistor: adding key
0000100710 [homekit] INFO: Persistor: save
0000100712 [homekit] INFO: Persistor: key added
0000102217 [homekit] INFO: Homekit progress callback: 7
0000102218 [homekit] INFO: writeData responseLen:220
0000102218 [homekit] INFO: Pairing completed.
0000103221 [homekit] INFO: Bonjour advertised
0000103221 [homekit] INFO: Client connected.
0000103223 [homekit] INFO: Request Message read length: 167 
0000103224 [homekit] INFO: Handling Pair Verify...
0000103225 [homekit] INFO: Homekit progress callback: 8
0000103225 [homekit] INFO: Pair Verify M1
0000104670 [homekit] INFO: Homekit progress callback: 9
0000104671 [homekit] INFO: writeData responseLen:220
0000105674 [homekit] INFO: Bonjour advertised
0000105676 [homekit] INFO: Request Message read length: 256 
0000105677 [homekit] INFO: Handling Pair Verify...
0000105678 [homekit] INFO: Pair Verify M3
0000105678 [homekit] INFO: Homekit progress callback: 10
0000105679 [homekit] INFO: Persistor: key get
0000105679 [homekit] INFO: Persistor: key found
0000106694 [homekit] INFO: Pair verified, secure connection established
0000106694 [homekit] INFO: Homekit progress callback: 11
0000106694 [homekit] INFO: writeData responseLen:81
0000106695 [homekit] INFO: Persistor: save
0000106697 [homekit] INFO: Bonjour advertised
0000107700 [homekit] INFO: Bonjour advertised
0000107702 [homekit] INFO: Request Message read length: 69 
0000107703 [homekit] INFO: Handling message request: accessories
0000107703 [homekit] INFO: Homekit progress callback: 12
0000107704 [homekit] INFO: Path: /accessories
0000107704 [homekit] INFO: Ask for accessories info
0000107707 [homekit] INFO: Accessories description len:704
0000107707 [homekit] INFO: Homekit progress callback: 13
0000107707 [homekit] INFO: writeEncryptedData responseLen:832
0000107808 [homekit] INFO: Response to: 192.168.1.174, data:HTTP/1.1 200 OK
Content-Type: application/hap+json
~ontent-Length: 704                                                    
HTTP/1.1 200 OK
Content-Type: application/hap+json
Content-Length: 704                                                    

{"accessories":[{"services":[{"iid":1,"type":"3E","characteristics":[{"value":"Motion Sensor","perms":["pr"],"type":"23","iid":2,"format":"string"},{"value":"Particle + ebaugh","perms":["pr"],"type":"20","iid":3,"format":"string"},{"value":"Motion","perms":["pr"],"type":"21","iid":4,"format":"string"},{"value":"1","perms":["pr"],"type":"30","iid":5,"format":"string"},{"value":"1.0.0","perms":["pr"],"type":"52","iid":6,"format":"string"},{"perms":["pw"],"type":"14","iid":7,"format":"bool"}]},{"iid":8,"type":"85","characteristics":[{"value":"Motion Sensor","perms":["pr"],"type":"23","iid":9,"format":"string"},{"value":"true","perms":["pr","ev"],"type":"22","iid":10,"format":"string"}]}],"aid":1}]}
0000108815 [homekit] INFO: Bonjour advertised
0000108817 [homekit] INFO: Request Message read length: 171 
0000108818 [homekit] INFO: Handling message request: pairings
0000108818 [homekit] INFO: Homekit progress callback: 12
0000108819 [homekit] INFO: Path: /pairings
0000108820 [homekit] INFO: 4
0000108820 [homekit] INFO: Delete user
0000108820 [homekit] INFO: Persistor: key exists
0000108821 [homekit] INFO: Persistor: key found
0000108821 [homekit] INFO: Persistor: save
0000108823 [homekit] INFO: Homekit progress callback: 13
0000108824 [homekit] INFO: writeEncryptedData responseLen:131
0000108924 [homekit] INFO: Response to: 192.168.1.174, data:HTTP/1.1 200 OK
Content-Type: application/pairing+tlv8
~ontent-Length: 3                                                  
HTTP/1.1 200 OK
Content-Type: application/pairing+tlv8
Content-Length: 3                                                  


0000109928 [homekit] INFO: Bonjour advertised
0000109929 [homekit] INFO: Client removed.
0000110932 [homekit] INFO: Bonjour advertised
0000111935 [homekit] INFO: Bonjour advertised
0000112938 [homekit] INFO: Bonjour advertised
0000113941 [homekit] INFO: Bonjour advertised
0000114944 [homekit] INFO: Bonjour advertised
0000115947 [homekit] INFO: Bonjour advertised

**Comment by earlthesquirrel** [comment]
That's a log captured via Serial (minus a few "Bonjour advertised" above and below.  Took me a few seconds to get code... that's why gap after starting to add..

**Comment by earlthesquirrel** [comment]
Any ideas?  I've tried with other Particles.
Same results.
Tried changing code, Tried chaining serial #, Tried commenting out handle function (aside from return).  Still no luck.

**Comment by ljezny** [comment]
Let me explain log:
1. Pair setup - creation of secure private and public key and it's exchange - it's ok
2. Pair verify - creation of secure connection between iPhone and Photon - it's ok
3. Accessories - iPhone asks Photon to describe itself as homekit accessory. Photon response is that JSON. 

After 3. iPhone disconnects and remove pairing. I am 90% sure that homekit accessory description is invalid.

**Comment by ljezny** [comment]
![Snímek obrazovky 2020-03-24 v 9 08 18](https://user-images.githubusercontent.com/1753433/77403025-dfd1e280-6daf-11ea-847c-c2d4c1a26f38.png)

I've checked the accessory JSON and at first look, you are definining characteristics with value:true and format:string.. seems strange

**Comment by ljezny** [comment]
Look into the documentation 8.23 Motion detected should be defined with format - bool

**Comment by earlthesquirrel** [comment]
I just now have time to write a final comment.
You were 100% correct.  I had some some debugging while waiting for your response and stumbled over the info about the value of the parameter.   I reached the answer right around the same time you replied 👍           

It definitely wasn't clear what the issue was... Homekit didn't give a very good error message.  Now I know to spend a lot of time reviewing the documentation when I get errors like this.  It was lack of experience debugging using this framework. 

Thanks so much for the info... and helping me sort this out (and confirming that what I thought was issue matched with your thoughts!!
