### ISSUE TITLE
irrigation system 

### ISSUE THREAD

**Issue by mf42** [ljezny/Particle-HAP#15]
Hi Lucas,
I'm not sure if the implementation of an irrigation system is still of interest.
I made some edits/enhancements (eg. linked services-> edit of the service class) of your code and it seems to run pretty fine. So if you want to take a look let me know.
Best, Michael

**Comment by ljezny** [comment]
Yes of course.

**Comment by mf42** [comment]
Dear Lucas,

Please find attached the collection of files I had to edit to implement the irrigation/faucet system  as well as an example.ino.

As you will see I added some virtual classes in your base classes so upward compatibility is not given. Please see all this as a kind of suggestion. 

In my case the system works fine („Siri, turn on sprinkler one for 5 minutes“). 

If you have questions, feel free. Happy to discuss, 

Best

Michael

**Comment by mf42** [comment]
ok, thanks.
