### ISSUE TITLE
Pairing stopped working unexpectedly - error -219

### ISSUE THREAD

**Issue by lazyatom** [ljezny/Particle-HAP#17]
I have a thermostat device set up that was working fine (thanks!) but after updating some stuff (this library from 1.0.12 to 1.0.16, and the device OS up to 1.5.2 but issue replicated with 1.4.4), pairing no longer works. Here's a sample of the log:

```
0000020116 [homekit] INFO: Bonjour advertised
0000021117 [homekit] INFO: Bonjour advertised
0000022118 [homekit] INFO: Bonjour advertised
0000023119 [homekit] INFO: Bonjour advertised
0000024120 [homekit] INFO: Bonjour advertised
0000024750 [homekit] INFO: Client connected.
0000024752 [homekit] INFO: Request Message read length: 128 
0000024753 [homekit] INFO: Handling Pair Setup...
0000024754 [homekit] INFO: State: 1
0000024754 [homekit] INFO: Homekit progress callback: 1
0000024754 [homekit] INFO: State_M1_SRPStartRequest
0000028688 [homekit] INFO: Homekit progress callback: 2
0000028689 [homekit] INFO: writeData responseLen:489
0000028693 [homekit] INFO: Bonjour advertised
0000028935 [homekit] INFO: Request Message read length: 581 
0000028936 [homekit] INFO: Handling Pair Setup...
0000028937 [homekit] INFO: State: 3
0000028938 [homekit] INFO: State_M3_SRPVerifyRequest
0000028938 [homekit] INFO: Homekit progress callback: 3
0000031995 [homekit] WARN: wc_SrpComputeKey: r:-2
0000031996 [homekit] WARN: wc_SrpVerifyPeersProof: r:-219
0000031996 [homekit] WARN: INCORRECT PASSWORD
0000031996 [homekit] INFO: Homekit progress callback: 999
0000031997 [homekit] INFO: writeData responseLen:84
0000032361 [homekit] INFO: Bonjour advertised
0000032363 [homekit] INFO: Request Message read length: 128 
0000032364 [homekit] INFO: Handling Pair Setup...
0000032365 [homekit] INFO: State: 1
0000032365 [homekit] INFO: Homekit progress callback: 1
0000032365 [homekit] INFO: State_M1_SRPStartRequest
0000036297 [homekit] INFO: Homekit progress callback: 2
0000036298 [homekit] INFO: writeData responseLen:489
0000036301 [homekit] INFO: Bonjour advertised
0000037301 [homekit] INFO: Bonjour advertised
0000038303 [homekit] INFO: Bonjour advertised
```

Error `-219` is `RP_VERIFY_E        = -219,  /* SRP proof verification failed. */`

I've tried setting the password to various different values, confirmed that it's correct by logging `hkServer->getPasscode().c_str()` on startup, restarted my phone, reset the `HKPersistor` and even cleared the EEPROM, with no success.

~~I'm 100% certain that the number I'm supplying to `HKServer` is the same as the one I'm entering into the phone. Any ideas what I can try next?~~

OK, so here's how I _did_ get it to work: instead of tapping on the accessory discovered by Bonjour, if I selected "Enter code" under "Manual code" and typed it in, and _then_ selected the accessory, the pairing seemed to work. I'm pretty sure I didn't have to do this before -- hopefully this is useful to someone else.

**Comment by ljezny** [comment]
Hello,
i am closing this, since it is now a know bug with Device OS 1.5.2. 
In Device 2.0.0 everything works just fine.
