### ISSUE TITLE
Device unresponsive more often in the last few days

### ISSUE THREAD

**Issue by lazyatom** [ljezny/Particle-HAP#19]
Not really an issue, but I was wondering if perhaps something had changed on the Apple side recently that intermittently broke this library? I have a Photon that's been running as a heating thermostat very happily for months, only needing the occasional restart, but over the past three days it now struggles to stay responsive when viewed from the Home app on my phone, sometimes requiring multiple resets before it comes back. I was just wondering if anyone else had seen that?

**Comment by Dids** [comment]
I've always had this. In fact, most of the time it shows up as offline on HomeKit's side, while Particle events are still flowing.
Eventually it seems to just die though, perhaps a leak somewhere?

**Comment by ljezny** [comment]
I hope it is now fixed with latest commit. I am closing the issue.
