### ISSUE TITLE
Updated services

### ISSUE THREAD

**Issue by DanielO** [ljezny/Particle-HAP#9]
Hi,
I am interesting in using this to control my sprinkler system but it seems the constants predate Apple's addition of irrigation valves.

For now I have just added some extra enums in my project header file but I am wondering if you have any plans on updating it?

Thanks.

**Comment by ljezny** [comment]
Hi,

i believe, if you add new services/characteristics to header files, it will works. 
I’ve attached the latest documentation (R2), where you can find all necessary constants.

PR are more than welcomed.

Also please share your project. I am interested. I have a homekit sprinkler from EVE (Bluettoth).

L.

S pozdravem
Ing. Lukáš Jezný
ljezny@gmail.com

**Comment by DanielO** [comment]
I wasn't sure if you had a plan or if I should just to a piece-meal pull request :)
I am happy to upload my project, hopefully soon!

The other issue is that I don't know how to get the Particle cloud compiler to use my version of the library - do you have any hints?

Thanks

**Comment by ljezny** [comment]
Hi,

i don’t plan it for now, i only add accessories and examples which i really needs for my projects :)

Well i have the same problem with cloud compiler, i solve it just by removing the reference to library and adding it locally. It’s bit of pain i know, but i didn’t find any better way.

L.

S pozdravem
Ing. Lukáš Jezný
ljezny@gmail.com

**Comment by DanielO** [comment]
OK thanks.
